### ISSUE TITLE
Crashing after connecting via VNC

### ISSUE THREAD

**Issue by BirknerAlex** [internap/docker-kvm-console-supermicro#8]
Hi!

I've build the Dockerfile now under Mac OS X Docker Version 1.12.5 (14777). After connecting via VNC I've got a timeout. 

I took a look into the /var/log/vnc-server.log inside the container. It seems the VNC server is crashing.

Stacktrace:
``` 21/12/2016 00:05:16 created   xdamage object: 0x400006
21/12/2016 00:05:17 read X11VNC_REMOTE: qry=wdpy_y
21/12/2016 00:05:17 read X11VNC_REMOTE: aro=wdpy_y:800
caught XIO error:
21/12/2016 00:05:17 deleted 1 tile_row polling images.

==> /var/log/x11-server.log <==
(EE) 
(EE) Backtrace:
(EE) 0: /usr/bin/Xvfb (xorg_backtrace+0x48) [0x564284351458]
(EE) 1: /usr/bin/Xvfb (0x5642841e7000+0x16e149) [0x564284355149]
(EE) 2: /lib/x86_64-linux-gnu/libpthread.so.0 (0x7f786f61d000+0x10330) [0x7f786f62d330]
(EE) 3: /lib/x86_64-linux-gnu/libc.so.6 (__select+0x13) [0x7f786e53cc33]
(EE) 4: /usr/bin/Xvfb (WaitForSomething+0x1ac) [0x56428434e99c]
(EE) 5: /usr/bin/Xvfb (0x5642841e7000+0x117121) [0x5642842fe121]
(EE) 6: /usr/bin/Xvfb (0x5642841e7000+0x11b25a) [0x56428430225a]
(EE) 7: /lib/x86_64-linux-gnu/libc.so.6 (__libc_start_main+0xf5) [0x7f786e46cf45]
(EE) 8: /usr/bin/Xvfb (0x5642841e7000+0x36c3e) [0x56428421dc3e]
(EE) 
(EE) Received signal 3 sent by process 1, uid 0
(EE) 
Fatal server error:
(EE) Caught signal 3 (Quit). Server aborting
(EE) 

==> /var/log/vnc-server.log <==
Error: Can't open display: (null)
Failed creating new xdo instance
Error: Can't open display: (null)
Failed creating new xdo instance
```

It seems also the Java process is crashing too:

```
2016-12-21 00:05:17
Full thread dump OpenJDK 64-Bit Server VM (24.121-b00 mixed mode):

"Thread-15" prio=10 tid=0x00007efdd806b000 nid=0x5e1 runnable [0x00007efde2992000]
   java.lang.Thread.State: RUNNABLE
	at tw.com.aten.vstorage.VirtualStorage.StartDev3Thread(Native Method)
	at tw.com.aten.vstorage.VirtualStorage$Dev3Thread.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

"Thread-14" prio=10 tid=0x00007efdd8069000 nid=0x5e0 runnable [0x00007efde2a93000]
   java.lang.Thread.State: RUNNABLE
	at tw.com.aten.vstorage.VirtualStorage.StartDev2Thread(Native Method)
	at tw.com.aten.vstorage.VirtualStorage$Dev2Thread.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

"Thread-13" prio=10 tid=0x00007efdd8067000 nid=0x5df runnable [0x00007efde2b94000]
   java.lang.Thread.State: RUNNABLE
	at tw.com.aten.vstorage.VirtualStorage.StartDev1Thread(Native Method)
	at tw.com.aten.vstorage.VirtualStorage$Dev1Thread.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

"Thread-12" prio=10 tid=0x00007efdd8066000 nid=0x5de runnable [0x00007efde2c95000]
   java.lang.Thread.State: RUNNABLE
	at tw.com.aten.vstorage.VirtualStorage.StartCheckDevExistThread(Native Method)
	at tw.com.aten.vstorage.VirtualStorage$C_DevExistThread.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
......... many more 
```

The server is running the IPMI version: 03.15 (Mainboard: X9SCL)

**Comment by mat128** [comment]
It seems to work on my end on a X9SCL machine running BMC firmware 1.64.
I upgraded the BMC to 3.19 and it still works perfectly. Can you try a different VNC client?

PS: Misread your version as 3.19 and now the machine has been upgraded. I can't find the 3.15 ROM. In any case, I do not think your problems are caused by the IPMI version but more of an environmental/configuration thing. Are you sure the container has access to the BMC?
